name: collatz

volumes:
  data:

services:

  db:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=collatz
    ports:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data/

  collatz:
    image: okteto.dev/collatz
    build:
      context: build/docker/main
    ports:
      - 8080            
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=collatz
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy


endpoints:
  - path: /
    service: collatz
    port: 8080              